import pygame

class Notify:
    ASK_FOR_STARTING_BUILDING, ASK_FOR_STARTING_LEVEL, ASK_FOR_STARTING_NODE, \
    ASK_FOR_DESTINATION_BUILDING, ASK_FOR_DESTINATION_LEVEL, ASK_FOR_DESTINATION_NODE,\
    TURN_RIGHT, TURN_LEFT, WALK_STRAIGHT, OBSTACLE_STOP, \
    
    CONFIRM_INPUT= range(7)

def output(notificationType, input):
    pass
